version: '3'
services:
  # my-app:
  # image: ${docker-registry}/my-app:1.0
  # ports:
  # - 3000:3000

  fastapi:
    build: .
    env_file:
      - .env
    container_name: fastapi
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8989 --reload"
    volumes:
      - .:/app
    ports:
      - "8989:8989"
    depends_on:
      - mongodb
    networks:
      - backend


  mongodb:
    image: mongo
    container_name: mongo
    env_file:
      - .env
    ports:
      - 27018:27017
    environment:
      - "MONGO_INITDB_DATABASE=${MONGO_DB}"
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  mongo-express-db:
    image: mongo-express
    container_name: mongo-express-db
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - 8083:8083
    environment:
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASS}"
      - "ME_CONFIG_MONGODB_SERVER=${MONGO_HOST}"

    networks:
      - backend
      
volumes:
  mongo-data:
    driver: local

networks:
  backend:
    driver: bridge
